name: Deploy vue app to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: ls
    - name: Checkout ðŸ›Ž
      uses: actions/checkout@main
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: |
        gcloud info
        echo ls
        ls
    - id: upload-file
      # uses: google-github-actions/upload-cloud-storage@main
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./
        destination: bizocean-portal-front

      # with:
      #   path: ../../../
      #   destination: bizocean-portal-front
      #   COMMIT_EMAIL: hoa.tran@rikai.technology
      #   COMMIT_NAME: PhuHoaRikai
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BASE_BRANCH: main # The branch you want to build
      #   DEPLOY_BRANCH: gh-pages # The branch you want to deploy
      #   BUILD_SCRIPT: yarn && yarn build # The build script
      #   FOLDER: dist # The folder generated by build script
      # run: ${{github.event.pull_request}}




    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - id: upload-file
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     path: ../../
    #     destination: bizocean-portal-front



        # credentials: ${{ secrets.gcp_credentials }}
# env:
# files: ${{steps.upload-files.outputs.uploaded}}
    # steps:
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    #   with:
    #       credentials: ${{ secrets.gcp_credentials }}
    #       path: ../
    #       destination: bizocean-portal-front


    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    #   with:
    #     credentials: ${{ secrets.gcp_credentials }}
    #     path: ../
    #     destination: bizocean-portal-front

    # steps:
    # - uses: actions/checkout@v2
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     version: '290.0.1'
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - run: gcloud info
      # uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      # with:
      #   path: ../
      #   destination: bizocean-portal-front

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@main

    # - name: Build
    #   run: |
    #     yarn install
    #     yarn build
    # - name: Build and Deploy
    #   uses: actions/setup-node@main
    #   with:
    #     COMMIT_EMAIL: hoa.tran@rikai.technology
    #     COMMIT_NAME: PhuHoaRikai
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BASE_BRANCH: main # The branch you want to build
    #     DEPLOY_BRANCH: gh-pages # The branch you want to deploy
    #     BUILD_SCRIPT: yarn && yarn build # The build script
    #     FOLDER: dist # The folder generated by build script

      # uses: actions/setup-node@main
      # with:
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BASE_BRANCH: main
      #   BRANCH: gh-pages
      #   FOLDER: .nuxt


