name: Deploy 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v1

    # - uses: jwalton/gh-find-current-pr@v1
    #   id: findPr
    # # This will echo "Your PR is 7", or be skipped if there is no current PR.
    # - run: echo "Your PR is ${PR} ------------- pull_request:${{github.event.pull_request.number}} number:${{ github.event.number }} ----
    #   if: success() && steps.findPr.outputs.number
    #   env:
    #     PR: ${{ steps.findPr.outputs.pr }}


    - name: Checkout ðŸ›Ž
      uses: actions/checkout@main
      if: github.event_name == 'pull_request'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      if: github.event_name == 'pull_request'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: |
        gcloud info
        echo ls
        ls
        echo ------------- ${{github.event.pull_request.number}} +++++ ${{ github.event.number }} ----
        echo "Your PR is ${PR} @@@@"
        echo "============= Your PR is >>> ${{ steps.findPr.outputs.pr }} <<< ==============="
        echo "============= github.event_name is >>> ${{ github.event_name }} <<< ==============="

    # - name: Install dependencies ðŸ‘¨ðŸ»â€ðŸ’»
    #   if: github.event_name == 'pull_request'
    #   run: yarn

    # - name: Build front ðŸ‘¨ðŸ»â€ðŸ’»
    #   if: github.event_name == 'pull_request'
    #   run: yarn build

    - id: uploaded-files
      uses: google-github-actions/upload-cloud-storage@main
      if: github.event_name == 'pull_request'
      with:
        path: pages
        destination: bizocean-portal-front/${{github.event.pull_request.number}}/pages/..
      # env:
      #   files: ${{steps.uploaded-files.outputs.uploaded}}

    - name: ssss
      run: echo "Your files is ${FILE_URL} ____ ${{steps.uploaded-files.outputs.uploaded}} +++ ${{steps.upload-files.outputs}} ___"

    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"




    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          github.issues.createComment({ issue_number, owner, repo, body: '${files}' });


    # - id: upload-file-story
    #   # uses: google-github-actions/upload-cloud-storage@main
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     path: ./storybook-static
    #     destination: bizocean-portal-front/front




      # with:
      #   path: ../../../
      #   destination: bizocean-portal-front
      #   COMMIT_EMAIL: hoa.tran@rikai.technology
      #   COMMIT_NAME: PhuHoaRikai
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BASE_BRANCH: main # The branch you want to build
      #   DEPLOY_BRANCH: gh-pages # The branch you want to deploy
      #   BUILD_SCRIPT: yarn && yarn build # The build script
      #   FOLDER: dist # The folder generated by build script
      # run: ${{github.event.pull_request}}




    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - id: upload-file
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     path: ../../
    #     destination: bizocean-portal-front



        # credentials: ${{ secrets.gcp_credentials }}
# env:
# files: ${{steps.upload-files.outputs.uploaded}}
    # steps:
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    #   with:
    #       credentials: ${{ secrets.gcp_credentials }}
    #       path: ../
    #       destination: bizocean-portal-front


    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
    #   with:
    #     credentials: ${{ secrets.gcp_credentials }}
    #     path: ../
    #     destination: bizocean-portal-front

    # steps:
    # - uses: actions/checkout@v2
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     version: '290.0.1'
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     export_default_credentials: true
    # - run: gcloud info
      # uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      # with:
      #   path: ../
      #   destination: bizocean-portal-front

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@main

    # - name: Build
    #   run: |
    #     yarn install
    #     yarn build
    # - name: Build and Deploy
    #   uses: actions/setup-node@main
    #   with:
    #     COMMIT_EMAIL: hoa.tran@rikai.technology
    #     COMMIT_NAME: PhuHoaRikai
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BASE_BRANCH: main # The branch you want to build
    #     DEPLOY_BRANCH: gh-pages # The branch you want to deploy
    #     BUILD_SCRIPT: yarn && yarn build # The build script
    #     FOLDER: dist # The folder generated by build script

      # uses: actions/setup-node@main
      # with:
      #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   BASE_BRANCH: main
      #   BRANCH: gh-pages
      #   FOLDER: .nuxt


